export const TOPICS: {
    [class_: string]: string[]
} = {
    "MATH 124": [
        "Tangent Lines",
        "Parametric Equations",
        "Limits",
        "Continuity",
        "Asymptotes",
        "Basic Derivatives",
        "Definition of a Derivative",
        "Product Rule",
        "Quotient Rule",
        "Chain Rule",
        "Trignometric Derivatives",
        "Exponential and Logarithmic Derivatives",
        "L'Hopital's Rule",
        "Implicit Differentiation",
        "Related Rates",
        "Linear Approximations",
        "Critical and Inflection Points",
        "Optimization",
        "Trigonometry",
        "Curve Sketching"
    ],
    "MATH 125": [
        "Indefinite Integrals",
        "Definite Integrals",
        "Basic Integrals",
        "Integrals by Substitution",
        "Integration by Parts",
        "Trigonometric Integrals",
        "Trigonometric Substitution",
        "Partial Fractions",
        "Improper Integrals",
        "Area Under/Between Curves",
        "Kinematics",
        "Work",
        "Numerical Integration",
        "Riemann Sums",
        "Fundamental Theorem of Calculus",
        "Volume by Disks/Washers",
        "Volume by Cylindrical Shells",
        "Average Value of a Function",
        "Arc Length",
        "Center of Mass",
        "Differential Equations"
    ],
    "MATH 126": [
        "Vector Operations",
        "3D Lines/Planes",
        "Quadric/Conic Surfaces",
        "Parameterized Curves",
        "Arc Length",
        "Curvature",
        "Tangent/Normal/Binormal Vectors",
        "Polar Coordinates",
        "Polar Curves",
        "Two-Variable Functions",
        "Partial Derivatives",
        "Tangent Planes",
        "Linear Approximations",
        "Gradients",
        "Critical Points",
        "Optimization",
        "Multivariable Riemann Sums",
        "Iterated Integrals",
        "Polar Form Integrals",
        "Center of Mass",
        "Taylor Polynomials",
        "Taylor Series",
        "Convergence Tests",
        "Taylor Series Manipulations"
    ]
}